FROM gcr.io/distroless/base-debian12:nonroot@sha256:4b5196599229a5cf312a676cfe1ee8587ecf2371dcc22620f8c7a66d77d125c8
ARG TARGETPLATFORM
COPY ${TARGETPLATFORM}/github-event-listener /usr/local/bin/github-event-listener
EXPOSE 8080
ENTRYPOINT ["github-event-listener"]
