FROM gcr.io/distroless/base-debian12:nonroot@sha256:8b9f2e503e55aff85b79d6b22c7a63a65170e8698ae80de680e3f5ea600977bf
ARG TARGETPLATFORM
COPY ${TARGETPLATFORM}/github-event-listener /usr/local/bin/github-event-listener
EXPOSE 8080
ENTRYPOINT ["github-event-listener"]
