FROM gcr.io/distroless/base-debian12:nonroot@sha256:7a75a36f4bec82a7542c64195e402907486f9a4dd2f8797a976aa0cf31cfb470
ARG TARGETPLATFORM
COPY ${TARGETPLATFORM}/github-event-listener /usr/local/bin/github-event-listener
EXPOSE 8080
ENTRYPOINT ["github-event-listener"]
